"""
Standalone seed data for PRISM engine.

Provides a fully populated TrendDatabase with ~35 realistic FMCG/HCB/LHC trends
and comprehensive competitor intelligence, replacing the need for an Excel file.

This enables PRISM to run standalone without external data dependencies.
"""

from datetime import datetime
from pulse.ingestion.models import Trend, TrendDatabase
from pulse.config import FORCES, CATEGORIES, REGIONS


def create_seed_database() -> TrendDatabase:
    """
    Create a fully populated TrendDatabase with ~35 realistic FMCG trends.

    Returns:
        TrendDatabase: Ready-to-use trend database with all forces represented
    """

    # ── CONSUMER FORCE (8 trends) ───────────────────────────────────────────
    consumer_trends = [
        Trend(
            id="consumer_01",
            force="Consumer",
            sub_category="Trends",
            name="Natural/Clean Beauty Movement",
            description="Growing consumer demand for products with natural origins, transparency on ingredients, and absence of synthetic chemicals. Driven by social media influencers and millennial purchasing patterns.",
            direction="Expansion",
            impact=5,
            probability=5,
            start_year=2024,
            strategic_implication="Henkel must reformulate Color and Care ranges with certified natural ingredients; opportunity to command premium pricing.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 5, "Hair: Styling": 3, "Hair: Body": 4,
                             "LHC: FCN": 3, "LHC: FCA": 2, "LHC: HDW": 2, "LHC: ADW": 2},
            vc_exposure={"Raw Materials": 5, "Formulation": 5, "Marketing": 5, "Consumer": 5},
            regional_exposure={"Europe": 5, "North America": 5, "Asia": 4, "High Growth": 2},
            data_source="Mintel Global Trends 2024, YouTube Beauty Influencers",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="consumer_02",
            force="Consumer",
            sub_category="Trends",
            name="Premiumization & Luxury Positioning",
            description="Shift toward high-end, professional-grade haircare and self-care products among affluent consumers. Beauty consumers increasingly willing to pay 2-3x for perceived quality and efficacy.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2023,
            strategic_implication="Grow premium Color and Care sub-brands (professional salon ranges); defend standard tier against private label.",
            category_exposure={"Hair: Color": 5, "Hair: Care": 5, "Hair: Styling": 4, "Hair: Body": 3,
                             "LHC: FCN": 2, "LHC: FCA": 2},
            vc_exposure={"Raw Materials": 3, "Formulation": 4, "Packaging": 4, "Marketing": 5, "Commercial": 4},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 5, "High Growth": 3},
            data_source="McKinsey Beauty & Personal Care 2024, Eurostat household expenditure",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="consumer_03",
            force="Consumer",
            sub_category="Demographics",
            name="Silver Generation Growth (55+ Age Group)",
            description="Fastest-growing demographic cohort in EMEA (55+ years old now ~28% of population). This group demands age-appropriate, efficacy-focused haircare and grooming solutions.",
            direction="Expansion",
            impact=4,
            probability=5,
            start_year=2022,
            strategic_implication="Launch dedicated grey/silver hair care lines (Color with toning, Body with anti-flake). Henkel's Palette brand underpositioned here.",
            category_exposure={"Hair: Color": 5, "Hair: Care": 4, "Hair: Styling": 2, "Hair: Body": 4,
                             "LHC: FCN": 1},
            vc_exposure={"Formulation": 4, "Marketing": 5, "Commercial": 4},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 3, "High Growth": 1},
            data_source="Eurostat Demographics 2024, Nielsen Consumer Panels",
            source_type="demographic_data",
            confidence="High",
        ),
        Trend(
            id="consumer_04",
            force="Consumer",
            sub_category="Behavior",
            name="DIY vs. Professional Salon Shift",
            description="Post-pandemic, consumers split into two camps: DIY home haircare (convenience, cost) and professional salon treatments (experience, quality). Mid-tier salons under pressure.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2021,
            strategic_implication="Dual-track strategy: mass-market DIY Color/Care at retail + professional product lines for salons (Toni&Guy). Cannibalization risk.",
            category_exposure={"Hair: Color": 5, "Hair: Care": 4, "Hair: Styling": 5, "Hair: Body": 2},
            vc_exposure={"Marketing": 4, "Commercial": 5},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 3, "High Growth": 2},
            data_source="Salon industry surveys, beauty retail transaction data",
            source_type="market_research",
            confidence="Medium",
        ),
        Trend(
            id="consumer_05",
            force="Consumer",
            sub_category="Sustainability",
            name="Sustainability Awareness Drives Purchase Decisions",
            description="65% of EU consumers now factor environmental impact into haircare purchases. Refillable packaging and carbon-neutral claims significantly influence category perception.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2023,
            strategic_implication="Accelerate refill/reuse systems for Care; communicate Henkel's sustainability commitments in Color packaging redesigns.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 5, "Hair: Styling": 2, "Hair: Body": 4,
                             "LHC: FCN": 4, "LHC: FCA": 3, "LHC: HDW": 3, "LHC: ADW": 3},
            vc_exposure={"Raw Materials": 3, "Packaging": 5, "Supply Chain": 5, "Marketing": 5},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 3, "High Growth": 2},
            data_source="GfK Sustainability Barometer 2024, EU Green Claims Survey",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="consumer_06",
            force="Consumer",
            sub_category="Behavior",
            name="Men's Grooming Growth & Masculinity Redefinition",
            description="Male personal care spending growing at 8-12% CAGR. Younger men (18-35) increasingly comfortable with dedicated hair/body care; trend toward inclusivity in branding.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2020,
            strategic_implication="Expand men's-focused Color (beard/stubble) and Body (premium grooming) lines; reposition as inclusive, not gendered.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 4, "Hair: Body": 5, "Hair: Styling": 4},
            vc_exposure={"Formulation": 3, "Marketing": 5, "Commercial": 4},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 3, "High Growth": 3},
            data_source="Kantar Euromonitor Men's Grooming, GQ Consumer Surveys",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="consumer_07",
            force="Consumer",
            sub_category="Trends",
            name="Gen Z Demand for Ingredient Transparency & Education",
            description="Gen Z consumers (18-25) demand not just products but education on WHY ingredients work. Instagram/TikTok 'hero ingredient' narratives drive category perception.",
            direction="Expansion",
            impact=3,
            probability=4,
            start_year=2022,
            strategic_implication="Build educational content around Color science (keratin, proteins) and Care actives; leverage creator partnerships.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 5, "Hair: Styling": 4, "Hair: Body": 4},
            vc_exposure={"Marketing": 5, "Commercial": 4},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 5, "High Growth": 3},
            data_source="Trend forecasting reports, TikTok/Instagram beauty trends",
            source_type="social_media",
            confidence="Medium",
        ),
        Trend(
            id="consumer_08",
            force="Consumer",
            sub_category="Behavior",
            name="Multi-Step Routines & Layering Behavior",
            description="Korean beauty influence driving adoption of multi-step skincare routines globally. Hair consumers increasingly adopt '10-step' regimens (cleanse, condition, treatment, serum, etc.).",
            direction="Expansion",
            impact=3,
            probability=3,
            start_year=2021,
            strategic_implication="Bundle Care products into 'system' kits; emphasize step-by-step regimens in communication.",
            category_exposure={"Hair: Care": 4, "Hair: Styling": 3},
            vc_exposure={"Formulation": 3, "Packaging": 3, "Marketing": 5},
            regional_exposure={"Europe": 3, "North America": 4, "Asia": 5, "High Growth": 2},
            data_source="Mintel K-Beauty Global Reports, salon booking data",
            source_type="market_research",
            confidence="Medium",
        ),
    ]

    # ── CUSTOMER FORCE (6 trends) ───────────────────────────────────────────
    customer_trends = [
        Trend(
            id="customer_01",
            force="Customer",
            sub_category="Channel Shift",
            name="Private Label Acceleration & Own-Brand Growth",
            description="Retail private labels now 35% of total haircare market in EMEA, growing at 6-8% vs. 2-3% for branded. Quality improvements and price positioning eroding brand equity.",
            direction="Contraction",
            impact=5,
            probability=5,
            start_year=2019,
            strategic_implication="Defend branded equity through innovation velocity; develop tiered strategy (ultra-premium, mainstream, value). Henkel potentially supplies own-label — revenue vs. brand risk?",
            category_exposure={"Hair: Color": 5, "Hair: Care": 5, "Hair: Styling": 4, "Hair: Body": 4,
                             "LHC: FCN": 4, "LHC: FCA": 4, "LHC: FFI": 4, "LHC: LAD": 4},
            vc_exposure={"Commercial": 5, "Marketing": 5},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 2, "High Growth": 2},
            data_source="IRI household panel, Euromonitor private label analysis",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="customer_02",
            force="Customer",
            sub_category="Channel Shift",
            name="E-commerce Channel Shift & Omnichannel Consolidation",
            description="Online beauty sales growing 15-20% CAGR; 60% of EU consumers now purchase beauty online. Amazon Beauty + direct-to-consumer channels reshaping distributor relationships.",
            direction="Expansion",
            impact=4,
            probability=5,
            start_year=2019,
            strategic_implication="Build DTC brands (Toni&Guy online, Henkel beauty direct); renegotiate distributor terms; invest in Amazon/Farfetch presence.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 5, "Hair: Styling": 4, "Hair: Body": 4,
                             "LHC: FFI": 3},
            vc_exposure={"Commercial": 5, "Marketing": 4},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 5, "High Growth": 3},
            data_source="eMarketer E-commerce EU 2024, Euromonitor online retail",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="customer_03",
            force="Customer",
            sub_category="Power Dynamics",
            name="Discounter Growth (Aldi, Lidl) & Channel Consolidation",
            description="Hard discounters capturing 25-30% of FMCG sales in core EMEA markets. Private label quality improvements mean consumers increasingly comfortable buying personal care at discounters.",
            direction="Contraction",
            impact=4,
            probability=5,
            start_year=2015,
            strategic_implication="Ensure Henkel products in discounter assortments (volume defense); develop entry-level branded lines for discounter placement.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 4, "Hair: Styling": 3, "Hair: Body": 3,
                             "LHC: FCN": 5, "LHC: FCA": 5, "LHC: FFI": 5, "LHC: LAD": 4},
            vc_exposure={"Commercial": 5},
            regional_exposure={"Europe": 5, "North America": 2, "Asia": 1, "High Growth": 1},
            data_source="Eurostat retail channel data, Nielsen distribution panels",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="customer_04",
            force="Customer",
            sub_category="Power Dynamics",
            name="Retail Media Networks & Shopper Data Monetization",
            description="Amazon Advertising, Tesco Media, and others now capturing 3-5% of beauty ad budgets. Retailers controlling consumer data = shift in power dynamics. CPG companies paying for shelf visibility online.",
            direction="Contraction",
            impact=3,
            probability=4,
            start_year=2022,
            strategic_implication="Budget reallocation: traditional trade spend → retail media. Henkel risks losing shelf space if underinvesting in Amazon/Tesco advertising.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 3, "Hair: Styling": 2, "Hair: Body": 2,
                             "LHC: FCN": 4, "LHC: FCA": 3},
            vc_exposure={"Commercial": 5, "Marketing": 5},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 3, "High Growth": 1},
            data_source="eMarketer Retail Media 2024, trade press",
            source_type="market_research",
            confidence="Medium",
        ),
        Trend(
            id="customer_05",
            force="Customer",
            sub_category="Channel Consolidation",
            name="Salon Channel Professionalization & Beauty Supply Shift",
            description="Professional salons shifting product sourcing directly from manufacturers (bypassing distributors). Brands establishing dedicated B2B-to-salon channels. Margin squeeze on independent distributors.",
            direction="Expansion",
            impact=3,
            probability=3,
            start_year=2020,
            strategic_implication="Invest in salon direct distribution; strengthen Toni&Guy professional channel; develop salon loyalty programs.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 4, "Hair: Styling": 5},
            vc_exposure={"Commercial": 5, "Supply Chain": 3},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 3, "High Growth": 2},
            data_source="Salon industry reports, beauty supply distribution surveys",
            source_type="market_research",
            confidence="Medium",
        ),
        Trend(
            id="customer_06",
            force="Customer",
            sub_category="Retail Format",
            name="Experiential Retail & Try-Before-You-Buy",
            description="Retail beauty shifting toward experience centers, color-matching tech, and personalized consultations (Ulta model). Static shelving declining; service-oriented formats growing.",
            direction="Expansion",
            impact=3,
            probability=4,
            start_year=2022,
            strategic_implication="Partner with retail on in-store beauty consultations; invest in Color-matching tech for retail.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 3, "Hair: Styling": 3},
            vc_exposure={"Commercial": 5, "Marketing": 3},
            regional_exposure={"Europe": 3, "North America": 5, "Asia": 4, "High Growth": 2},
            data_source="Retail trends reports, experiential retail case studies",
            source_type="market_research",
            confidence="Medium",
        ),
    ]

    # ── TECHNOLOGY FORCE (7 trends) ─────────────────────────────────────────
    technology_trends = [
        Trend(
            id="technology_01",
            force="Technology",
            sub_category="Digital",
            name="AI-Driven Personalization & Beauty Tech",
            description="AI-powered color-matching (Pantene Virtual Try-On, L'Oréal ModiFace), personalized product recommendations, and skin/hair diagnostics. Consumers expect customized solutions; mass production declining.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2023,
            strategic_implication="Invest in AI-powered Color matching tool; develop algorithmic product recommendation engine for e-commerce.",
            category_exposure={"Hair: Color": 5, "Hair: Care": 4, "Hair: Styling": 3},
            vc_exposure={"Formulation": 2, "Marketing": 5, "Consumer": 4},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 5, "High Growth": 2},
            data_source="Gartner Beauty Tech Report 2024, brand press releases",
            source_type="technology_reports",
            confidence="High",
        ),
        Trend(
            id="technology_02",
            force="Technology",
            sub_category="Biotech",
            name="Fermentation & Biotech Ingredients",
            description="Shift toward sustainable, lab-grown ingredients (biotech proteins, fermentation-derived actives) replacing petrochemical and plant-derived inputs. Impossible Foods model applied to beauty.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2023,
            strategic_implication="Partner with biotech (Geno, Bolt Threads) for sustainable proteins; reformulate Care with fermentation-derived conditioning agents.",
            category_exposure={"Hair: Care": 5, "Hair: Color": 3, "Hair: Body": 3,
                             "LHC: FCN": 3, "LHC: FCA": 3},
            vc_exposure={"Raw Materials": 5, "Formulation": 5},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 3, "High Growth": 1},
            data_source="Nature journal biotech articles, brand innovation pipeline disclosures",
            source_type="scientific_research",
            confidence="High",
        ),
        Trend(
            id="technology_03",
            force="Technology",
            sub_category="Materials",
            name="Smart Packaging & IoT-Enabled Products",
            description="Connected packaging (QR codes with AR try-ons, RFID authentication, smart dispensers). Henkel investing in PackTrack; consumers expect 'smart' product experiences.",
            direction="Expansion",
            impact=3,
            probability=3,
            start_year=2023,
            strategic_implication="Upgrade packaging with QR/AR integration; develop refillable smart dispensers for Color/Care.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 3, "Hair: Styling": 2, "Hair: Body": 2},
            vc_exposure={"Packaging": 5, "Consumer": 3},
            regional_exposure={"Europe": 3, "North America": 4, "Asia": 5, "High Growth": 1},
            data_source="PackagingTechnology reports, Henkel investor materials",
            source_type="technology_reports",
            confidence="Medium",
        ),
        Trend(
            id="technology_04",
            force="Technology",
            sub_category="Manufacturing",
            name="Waterless Formulations & Powder Alternatives",
            description="Consumer shift toward concentrated, waterless haircare (powders, bars, pastes). Henkel 2024 sustainability target = 25% waterless products. Manufacturing capex required.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2023,
            strategic_implication="Accelerate waterless Color and Care lines; invest in powder formulation R&D and production capacity.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 4, "Hair: Styling": 4, "Hair: Body": 3,
                             "LHC: FCN": 3, "LHC: FCA": 3},
            vc_exposure={"Formulation": 5, "Manufacturing": 5, "Packaging": 4},
            regional_exposure={"Europe": 4, "North America": 4, "Asia": 3, "High Growth": 4},
            data_source="Henkel sustainability reports, industry trends",
            source_type="market_research",
            confidence="High",
        ),
        Trend(
            id="technology_05",
            force="Technology",
            sub_category="Materials",
            name="Biodegradable & Plastic-Alternative Packaging",
            description="Phase-out of single-use plastics accelerating; brands moving to biodegradable pouches, PHA films, and paper-based packaging. Regulatory deadlines (EU 2030) driving adoption.",
            direction="Expansion",
            impact=4,
            probability=5,
            start_year=2021,
            strategic_implication="Full migration of Color/Care to sustainable packaging by 2028; negotiate volume commitments with biofilm suppliers.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 4, "Hair: Styling": 4, "Hair: Body": 4,
                             "LHC: FCN": 4, "LHC: FCA": 4, "LHC: FFI": 4, "LHC: LAD": 4},
            vc_exposure={"Packaging": 5, "Supply Chain": 4},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 3, "High Growth": 2},
            data_source="EU Packaging Directive reports, brand sustainability commitments",
            source_type="regulatory",
            confidence="High",
        ),
        Trend(
            id="technology_06",
            force="Technology",
            sub_category="Digital",
            name="Direct-to-Consumer Tech Platforms & Subscription Models",
            description="Brands launching DTC subscription services (shampoo/conditioner auto-replenishment). Henkel exploring subscription for Toni&Guy and Schwarzkopf lines. Data capture and retention benefits.",
            direction="Expansion",
            impact=3,
            probability=4,
            start_year=2022,
            strategic_implication="Launch DTC subscription pilot for premium Color/Care lines; build loyalty data infrastructure.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 4, "Hair: Styling": 2},
            vc_exposure={"Commercial": 5, "Consumer": 4},
            regional_exposure={"Europe": 3, "North America": 5, "Asia": 3, "High Growth": 1},
            data_source="Subscription beauty platforms, brand announcements",
            source_type="market_research",
            confidence="Medium",
        ),
        Trend(
            id="technology_07",
            force="Technology",
            sub_category="Digital",
            name="Supply Chain Visibility & Blockchain Authentication",
            description="Brands implementing blockchain for ingredient traceability and anti-counterfeiting. Consumers increasingly demand proof of sustainability claims. Henkel investing in supply chain tech.",
            direction="Expansion",
            impact=3,
            probability=3,
            start_year=2023,
            strategic_implication="Pilot blockchain for premium Color line; communicate transparency to consumers via blockchain verification.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 3},
            vc_exposure={"Supply Chain": 4, "Marketing": 3},
            regional_exposure={"Europe": 4, "North America": 4, "Asia": 3, "High Growth": 1},
            data_source="Blockchain beauty initiatives, sustainability reporting",
            source_type="technology_reports",
            confidence="Medium",
        ),
    ]

    # ── GOVERNMENT FORCE (6 trends) ─────────────────────────────────────────
    government_trends = [
        Trend(
            id="government_01",
            force="Government",
            sub_category="Regulation",
            name="EU Microplastics Ban & REACH Restrictions",
            description="EU has banned microplastics in cosmetics (2023 effective); microbeads in rinse-off products phased out. Further restrictions on polymers in color rinses expected 2025-2026.",
            direction="Contraction",
            impact=4,
            probability=5,
            start_year=2023,
            strategic_implication="Immediate reformulation of rinse-off color products; shift to biodegradable polymers. Significant R&D cost.",
            category_exposure={"Hair: Color": 5, "Hair: Care": 4, "Hair: Body": 3},
            vc_exposure={"Formulation": 5, "Raw Materials": 4},
            regional_exposure={"Europe": 5, "North America": 3, "Asia": 2, "High Growth": 1},
            data_source="ECHA Cosmetics Regulation, EU Official Journal",
            source_type="regulatory",
            confidence="High",
        ),
        Trend(
            id="government_02",
            force="Government",
            sub_category="Regulation",
            name="PFAS Restrictions & 'Forever Chemicals' Phase-Out",
            description="EU PFOA/PFOS bans expanding to all PFAS ('GenX' restrictions 2024-2025). Brands must replace fluorine-based water/oil repellents in packaging and formulations.",
            direction="Contraction",
            impact=4,
            probability=5,
            start_year=2024,
            strategic_implication="Audit all formulations and packaging for PFAS; invest in PFAS-free alternatives (silicon-based, wax coatings).",
            category_exposure={"Hair: Color": 3, "Hair: Care": 3, "Hair: Body": 2,
                             "LHC: FCN": 4, "LHC: FCA": 3, "LHC: HDW": 3},
            vc_exposure={"Raw Materials": 4, "Packaging": 4},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 2, "High Growth": 1},
            data_source="ECHA PFAS restrictions, EPA GenX decisions",
            source_type="regulatory",
            confidence="High",
        ),
        Trend(
            id="government_03",
            force="Government",
            sub_category="Regulation",
            name="EU Green Claims Directive & Substantiation Burden",
            description="2024 enforcement of Green Claims Directive: 'sustainable,' 'eco-friendly,' 'natural' claims must be independently verified. Burden of proof on brands. Non-compliance fines up to 10% revenue.",
            direction="Contraction",
            impact=4,
            probability=5,
            start_year=2024,
            strategic_implication="Audit all sustainability claims on Color/Care; invest in third-party certification; retrain marketing on claim substantiation.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 5, "Hair: Styling": 3, "Hair: Body": 4},
            vc_exposure={"Marketing": 5, "Consumer": 3},
            regional_exposure={"Europe": 5, "North America": 3, "Asia": 2, "High Growth": 1},
            data_source="EU Green Claims Directive (2023/2673), EFTA Surveillance Authority guidance",
            source_type="regulatory",
            confidence="High",
        ),
        Trend(
            id="government_04",
            force="Government",
            sub_category="Regulation",
            name="Extended Producer Responsibility (EPR) & Packaging Tax",
            description="EU member states expanding EPR schemes (producer pays for end-of-life packaging). Germany, France introducing packaging taxes. Cost-per-unit packaging expected to increase 15-25% by 2026.",
            direction="Contraction",
            impact=4,
            probability=5,
            start_year=2024,
            strategic_implication="Switch to lighter, minimal packaging; invest in reusable/refillable systems to offset EPR costs.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 4, "Hair: Styling": 3, "Hair: Body": 3,
                             "LHC: FCN": 4, "LHC: FCA": 4, "LHC: FFI": 3, "LHC: LAD": 3},
            vc_exposure={"Packaging": 5, "Supply Chain": 4},
            regional_exposure={"Europe": 5, "North America": 3, "Asia": 2, "High Growth": 1},
            data_source="EU directive 2024/1940, national EPR schemes",
            source_type="regulatory",
            confidence="High",
        ),
        Trend(
            id="government_05",
            force="Government",
            sub_category="Regulation",
            name="Natural vs Synthetic Ingredient Labeling Requirements",
            description="EU considering mandatory disclosure of 'natural %' in formulations. Debate ongoing but likely implementation 2025-2026. Will favor brands with high natural content.",
            direction="Expansion",
            impact=3,
            probability=4,
            start_year=2025,
            strategic_implication="Reformulate Color/Care with higher natural ingredient %age; prepare labeling strategy.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 5, "Hair: Styling": 2, "Hair: Body": 3},
            vc_exposure={"Formulation": 5, "Raw Materials": 4, "Marketing": 3},
            regional_exposure={"Europe": 5, "North America": 3, "Asia": 2, "High Growth": 1},
            data_source="EU cosmetics labeling proposals, industry working groups",
            source_type="regulatory",
            confidence="Medium",
        ),
        Trend(
            id="government_06",
            force="Government",
            sub_category="Regulation",
            name="Cosmetics Ingredient Restrictions (Allergens, Preservatives)",
            description="SCCS (EU Scientific Committee) expanding restriction list on allergens, preservatives, and UV filters. 2024-2026: likely restrictions on common preservatives (methylisothiazolinone), fragrance allergens.",
            direction="Contraction",
            impact=3,
            probability=4,
            start_year=2024,
            strategic_implication="Proactive ingredient substitution; stay ahead of SCCS decisions to avoid last-minute reformulation crises.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 3, "Hair: Body": 3},
            vc_exposure={"Formulation": 4, "Raw Materials": 3},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 3, "High Growth": 1},
            data_source="SCCS opinions, EU cosmetics regulatory database",
            source_type="regulatory",
            confidence="Medium",
        ),
    ]

    # ── ENVIRONMENTAL FORCE (5 trends) ──────────────────────────────────────
    environmental_trends = [
        Trend(
            id="environmental_01",
            force="Environmental",
            sub_category="Climate",
            name="Water Scarcity & Supply Chain Disruption",
            description="Global freshwater stress accelerating; Europe faces summer droughts. Manufacturing water consumption + agricultural inputs at risk. Rising water costs impacting formula economics.",
            direction="Contraction",
            impact=4,
            probability=4,
            start_year=2022,
            strategic_implication="Accelerate waterless formulations; source water-efficient raw materials; invest in manufacturing water recycling tech.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 4, "Hair: Styling": 2, "Hair: Body": 3,
                             "LHC: FCN": 4, "LHC: FCA": 4},
            vc_exposure={"Raw Materials": 4, "Manufacturing": 4, "Supply Chain": 4},
            regional_exposure={"Europe": 4, "North America": 3, "Asia": 4, "High Growth": 5},
            data_source="World Resources Institute water stress maps, manufacturing sustainability reports",
            source_type="environmental",
            confidence="High",
        ),
        Trend(
            id="environmental_02",
            force="Environmental",
            sub_category="Climate",
            name="Raw Material Volatility (Palm, Coconut, Protein)",
            description="Climate volatility driving 20-40% price swings in key inputs (palm oil, coconut, proteins). Crop failures in SE Asia, Africa impacting supply. Hedging costs rising.",
            direction="Contraction",
            impact=4,
            probability=4,
            start_year=2020,
            strategic_implication="Diversify supplier base; invest in synthetic/biotech alternatives (fermented proteins); lock in long-term contracts.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 5, "Hair: Styling": 3, "Hair: Body": 4,
                             "LHC: FCN": 5, "LHC: FCA": 4},
            vc_exposure={"Raw Materials": 5, "Supply Chain": 5},
            regional_exposure={"Europe": 4, "North America": 3, "Asia": 5, "High Growth": 5},
            data_source="commodity price indices (CBOT, ICE), agricultural sustainability reports",
            source_type="environmental",
            confidence="High",
        ),
        Trend(
            id="environmental_03",
            force="Environmental",
            sub_category="Circular Economy",
            name="Refill/Reuse Systems & Circular Economy Adoption",
            description="Brands adopting refill/reuse models (Patagonia, Unilever's Refill initiatives). Consumers shifting toward refillable packaging. Potential 30-40% reduction in new package volume.",
            direction="Expansion",
            impact=4,
            probability=4,
            start_year=2021,
            strategic_implication="Scale refill programs for Color/Care; invest in refill infrastructure (store dispensers, home-delivery refills). Revenue per unit lower but margin structure TBD.",
            category_exposure={"Hair: Color": 3, "Hair: Care": 5, "Hair: Styling": 2, "Hair: Body": 3,
                             "LHC: FCN": 4, "LHC: FCA": 3},
            vc_exposure={"Packaging": 5, "Commercial": 4, "Supply Chain": 3},
            regional_exposure={"Europe": 5, "North America": 3, "Asia": 2, "High Growth": 1},
            data_source="Ellen MacArthur Foundation, brand sustainability disclosures",
            source_type="environmental",
            confidence="High",
        ),
        Trend(
            id="environmental_04",
            force="Environmental",
            sub_category="Carbon",
            name="Carbon Neutral & Net-Zero Supply Chain Requirements",
            description="Corporate net-zero commitments (Henkel 2030 target) now linked to procurement. Suppliers unable to reduce emissions face de-listing. Carbon cost pass-through beginning.",
            direction="Contraction",
            impact=3,
            probability=5,
            start_year=2024,
            strategic_implication="Audit Tier-2/3 supplier emissions; invest in renewable energy for manufacturing; source carbon-neutral ingredients (premium cost).",
            category_exposure={"Hair: Color": 3, "Hair: Care": 3, "Hair: Styling": 2, "Hair: Body": 2,
                             "LHC: FCN": 4, "LHC: FCA": 3},
            vc_exposure={"Manufacturing": 5, "Supply Chain": 5},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 3, "High Growth": 2},
            data_source="Henkel sustainability reports, CDP supply chain data",
            source_type="environmental",
            confidence="High",
        ),
        Trend(
            id="environmental_05",
            force="Environmental",
            sub_category="Biodiversity",
            name="Biodiversity Loss & Habitat-Conscious Sourcing",
            description="Nature loss becoming regulatory/reputational risk. Brands facing pressure to avoid sourcing from biodiverse regions without conservation commitments. Certification costs rising.",
            direction="Contraction",
            impact=3,
            probability=4,
            start_year=2023,
            strategic_implication="Implement biodiversity assessments for key raw material sourcing; partner with conservation orgs; achieve FSC/Rainforest Alliance certification.",
            category_exposure={"Hair: Color": 2, "Hair: Care": 3, "Hair: Body": 2,
                             "LHC: FCN": 3, "LHC: FCA": 2},
            vc_exposure={"Raw Materials": 5, "Supply Chain": 3},
            regional_exposure={"Europe": 4, "North America": 3, "Asia": 4, "High Growth": 5},
            data_source="IUCN biodiversity reports, ESG reporting frameworks",
            source_type="environmental",
            confidence="Medium",
        ),
    ]

    # ── COMPETITIVE FORCE (3 trends) ────────────────────────────────────────
    competitive_trends = [
        Trend(
            id="competitive_01",
            force="Competitive",
            sub_category="Competitive Dynamics",
            name="P&G & L'Oréal Innovation Velocity & Market Share Pressure",
            description="P&G Pantene and L'Oréal Paris accelerating innovation cycles (6-month vs 12-month releases). Market share pressure in Color and Care. Pricing power shifting toward mega-brands.",
            direction="Contraction",
            impact=5,
            probability=5,
            start_year=2020,
            strategic_implication="Henkel must match innovation pace; invest in Color/Care R&D pipeline; consider acquisition of niche brands for innovation.",
            category_exposure={"Hair: Color": 5, "Hair: Care": 5, "Hair: Styling": 4,
                             "LHC: FCN": 3, "LHC: FCA": 3},
            vc_exposure={"Formulation": 5, "Marketing": 5},
            regional_exposure={"Europe": 5, "North America": 5, "Asia": 4, "High Growth": 3},
            data_source="Competitive patent analysis, brand launch tracking",
            source_type="competitive",
            confidence="High",
        ),
        Trend(
            id="competitive_02",
            force="Competitive",
            sub_category="Competitive Dynamics",
            name="Direct-to-Consumer Brands & Niche Disruptors",
            description="D2C beauty brands (Olaplex, K18, Curlsmith) capturing premiumization trend. DTC brands now 8-12% of color/care category. Traditional brands losing shelf space to indie brands.",
            direction="Contraction",
            impact=4,
            probability=5,
            start_year=2019,
            strategic_implication="Henkel's Schwarzkopf, Toni&Guy build DTC; consider acquisition of cult indie brands; invest in Amazon/Sephora presence.",
            category_exposure={"Hair: Color": 4, "Hair: Care": 5, "Hair: Styling": 4},
            vc_exposure={"Commercial": 5, "Marketing": 5},
            regional_exposure={"Europe": 4, "North America": 5, "Asia": 3, "High Growth": 2},
            data_source="indie brand market share data, investor presentations",
            source_type="competitive",
            confidence="High",
        ),
        Trend(
            id="competitive_03",
            force="Competitive",
            sub_category="Pricing Dynamics",
            name="Price War in Laundry & All-Temp Detergent Segment",
            description="Private label detergents (LHC:FCN, FCA) gaining via aggressive pricing. Reckitt Lysol defending via promotion. Margin compression 10-15% expected in mass-market segments.",
            direction="Contraction",
            impact=4,
            probability=4,
            start_year=2022,
            strategic_implication="Defend mainstream FCN/FCA via innovation (cold-water performance, sustainability). Shift mix toward premium segments (specialty detergents).",
            category_exposure={"LHC: FCN": 5, "LHC: FCA": 5, "LHC: FFI": 3},
            vc_exposure={"Commercial": 5, "Marketing": 4},
            regional_exposure={"Europe": 5, "North America": 4, "Asia": 3, "High Growth": 3},
            data_source="competitive pricing databases, analyst reports",
            source_type="competitive",
            confidence="Medium",
        ),
    ]

    # Combine all trends
    all_trends = (consumer_trends + customer_trends + technology_trends +
                  government_trends + environmental_trends + competitive_trends)

    # Create and return TrendDatabase
    db = TrendDatabase(
        trends=all_trends,
        categories=list(CATEGORIES),
        forces=list(FORCES),
        source_file="seed_data.py",
        ingestion_date=datetime.now(),
        financial_data_detected=False,
    )

    return db


def get_competitor_profiles() -> list[dict]:
    """
    Get detailed profiles for 12+ key competitors.

    Returns:
        list[dict]: Competitor intelligence (public data only) as dicts
    """

    return [
        {
            "id": "pg",
            "name": "Procter & Gamble",
            "archetype": "premium_defender",
            "hair_exposure": 0.85,
            "lhc_exposure": 0.75,
            "response_speed": "fast",
            "typical_responses": {
                "price_war": "defend_with_innovation",
                "regulation": "lobby_and_comply_early",
                "tech_disruption": "fast_follower",
                "private_label": "premiumize_further",
            },
            "category_exposure": {
                "Hair: Color": 0.9, "Hair: Care": 0.95, "Hair: Styling": 0.85, "Hair: Body": 0.8,
                "LHC: FCN": 0.7, "LHC: FCA": 0.75, "LHC: FFI": 0.6, "LHC: LAD": 0.65,
            },
        },
        {
            "id": "loreal",
            "name": "L'Oréal",
            "archetype": "innovation_leader",
            "hair_exposure": 0.9,
            "lhc_exposure": 0.4,
            "response_speed": "fast",
            "typical_responses": {
                "price_war": "abandon_mass_market_gradually",
                "regulation": "lead_compliance",
                "tech_disruption": "acquire",
                "private_label": "focus_premium",
            },
            "category_exposure": {
                "Hair: Color": 0.95, "Hair: Care": 0.85, "Hair: Styling": 0.8, "Hair: Body": 0.5,
                "LHC: FCN": 0.1, "LHC: FCA": 0.1,
            },
        },
        {
            "id": "unilever",
            "name": "Unilever",
            "archetype": "sustainability_leader",
            "hair_exposure": 0.7,
            "lhc_exposure": 0.8,
            "response_speed": "medium",
            "typical_responses": {
                "price_war": "portfolio_rationalization",
                "regulation": "lead_compliance",
                "tech_disruption": "acquire",
                "private_label": "value_tier_launch",
            },
            "category_exposure": {
                "Hair: Color": 0.6, "Hair: Care": 0.7, "Hair: Styling": 0.5, "Hair: Body": 0.6,
                "LHC: FCN": 0.85, "LHC: FCA": 0.8, "LHC: FFI": 0.7, "LHC: LAD": 0.75,
            },
        },
        {
            "id": "reckitt",
            "name": "Reckitt Benckiser",
            "archetype": "hygiene_specialist",
            "hair_exposure": 0.2,
            "lhc_exposure": 0.9,
            "response_speed": "medium",
            "typical_responses": {
                "price_war": "defend_core_categories",
                "regulation": "comply_minimum",
                "tech_disruption": "selective_adoption",
                "private_label": "innovation_premiumization",
            },
            "category_exposure": {
                "Hair: Color": 0.05, "Hair: Care": 0.1,
                "LHC: FCN": 0.95, "LHC: FCA": 0.9, "LHC: HDW": 0.85,
            },
        },
        {
            "id": "colgate",
            "name": "Colgate-Palmolive",
            "archetype": "oral_and_personal_care",
            "hair_exposure": 0.3,
            "lhc_exposure": 0.6,
            "response_speed": "slow",
            "typical_responses": {
                "price_war": "defend_via_distribution",
                "regulation": "comply_on_schedule",
                "tech_disruption": "late_follower",
                "private_label": "compete_on_price",
            },
            "category_exposure": {
                "Hair: Color": 0.15, "Hair: Care": 0.35, "Hair: Body": 0.4,
                "LHC: FCN": 0.5, "LHC: FCA": 0.45,
            },
        },
        {
            "id": "beiersdorf",
            "name": "Beiersdorf (Nivea, Eucerin, tesa)",
            "archetype": "skincare_leader",
            "hair_exposure": 0.2,
            "lhc_exposure": 0.3,
            "response_speed": "medium",
            "typical_responses": {
                "price_war": "defend_brand_positioning",
                "regulation": "proactive_compliance",
                "tech_disruption": "selective_partnership",
                "private_label": "premium_positioning",
            },
            "category_exposure": {
                "Hair: Body": 0.5,
                "LHC: FCN": 0.2,
            },
        },
        {
            "id": "kao",
            "name": "Kao Corporation",
            "archetype": "asian_conglomerate",
            "hair_exposure": 0.6,
            "lhc_exposure": 0.5,
            "response_speed": "medium",
            "typical_responses": {
                "price_war": "compete_with_innovation",
                "regulation": "adapt_by_market",
                "tech_disruption": "invest_heavily",
                "private_label": "premium_only",
            },
            "category_exposure": {
                "Hair: Color": 0.4, "Hair: Care": 0.65, "Hair: Styling": 0.4,
                "LHC: FCN": 0.3, "LHC: FCA": 0.3,
            },
        },
        {
            "id": "haleon",
            "name": "Haleon (GSK spin-out)",
            "archetype": "health_and_wellness",
            "hair_exposure": 0.3,
            "lhc_exposure": 0.6,
            "response_speed": "fast",
            "typical_responses": {
                "price_war": "move_upmarket",
                "regulation": "lead_compliance",
                "tech_disruption": "invest_in_science",
                "private_label": "avoid",
            },
            "category_exposure": {
                "Hair: Care": 0.4, "Hair: Body": 0.35,
                "LHC: FCN": 0.4, "LHC: FCA": 0.35,
            },
        },
        {
            "id": "kenvue",
            "name": "Kenvue (J&J spin-out)",
            "archetype": "consumer_health_focus",
            "hair_exposure": 0.25,
            "lhc_exposure": 0.4,
            "response_speed": "medium",
            "typical_responses": {
                "price_war": "defend_distribution",
                "regulation": "proactive",
                "tech_disruption": "collaborate",
                "private_label": "compete_on_value",
            },
            "category_exposure": {
                "Hair: Body": 0.3,
                "LHC: FCN": 0.25,
            },
        },
        {
            "id": "church_dwight",
            "name": "Church & Dwight",
            "archetype": "value_and_natural",
            "hair_exposure": 0.15,
            "lhc_exposure": 0.65,
            "response_speed": "slow",
            "typical_responses": {
                "price_war": "compete_on_price",
                "regulation": "comply_on_deadline",
                "tech_disruption": "acquire_innovation",
                "private_label": "undercut_price",
            },
            "category_exposure": {
                "LHC: FCN": 0.7, "LHC: FCA": 0.65,
            },
        },
        {
            "id": "clorox",
            "name": "The Clorox Company",
            "archetype": "cleaning_and_bleach",
            "hair_exposure": 0.0,
            "lhc_exposure": 0.8,
            "response_speed": "medium",
            "typical_responses": {
                "price_war": "defend_volume",
                "regulation": "comply_strictly",
                "tech_disruption": "selective_adoption",
                "private_label": "compete_on_price",
            },
            "category_exposure": {
                "LHC: FCN": 0.75, "LHC: FCA": 0.6, "LHC: HDW": 0.8,
            },
        },
        {
            "id": "scjohnson",
            "name": "SC Johnson",
            "archetype": "family_company",
            "hair_exposure": 0.05,
            "lhc_exposure": 0.7,
            "response_speed": "slow",
            "typical_responses": {
                "price_war": "defend_core_brands",
                "regulation": "comply_minimum",
                "tech_disruption": "late_follower",
                "private_label": "compete_on_price",
            },
            "category_exposure": {
                "LHC: FCN": 0.5, "LHC: HDW": 0.65,
            },
        },
    ]


def get_seed_competitive_intelligence() -> dict:
    """
    Get comprehensive competitive intelligence (public data only).

    Returns:
        dict: Detailed market dynamics, category intensity, competitor moves
    """

    return {
        "competitors": {
            "pg": {
                "name": "Procter & Gamble",
                "hq": "Cincinnati, Ohio, USA",
                "relevant_brands": {
                    "Hair": ["Pantene", "Head & Shoulders", "Herbal Essences", "Wella"],
                    "LHC": ["Tide", "Ariel", "Fairy", "Cascade", "Swiffer"],
                },
                "strategic_focus": "Scale premium prestige; accelerate innovation velocity in Color (5x line extensions 2023-24)",
                "recent_moves": [
                    "Launched Pantene Gold Series (premium aged hair)",
                    "Invested $1B+ in 'beautytech' partnerships",
                    "Expanded professional salon distribution globally",
                    "Acquired Tarte Cosmetics platform",
                ],
                "strengths": [
                    "Scale advantage in supply chain",
                    "Innovation velocity (6-month product cycles)",
                    "Distribution reach (80%+ retail)",
                    "Premium brand portfolio depth",
                ],
                "weaknesses": [
                    "Perception of legacy brand (Pantene aged positioning)",
                    "Slower to naturals/clean beauty shift vs indie brands",
                    "Higher price points vulnerable to private label",
                ],
                "category_threat_level": {
                    "Hair: Color": "Very High",
                    "Hair: Care": "Very High",
                    "Hair: Styling": "High",
                    "Hair: Body": "High",
                    "LHC: FCN": "High",
                    "LHC: FCA": "Medium",
                },
            },
            "loreal": {
                "name": "L'Oréal",
                "hq": "Paris, France",
                "relevant_brands": {
                    "Hair": ["L'Oréal Paris", "L'Oréal Professionnel", "Garnier", "Kérastase", "Redken", "Pureology"],
                },
                "strategic_focus": "Luxury positioning + innovation in personalization (AI color matching)",
                "recent_moves": [
                    "Launched ModiFace virtual try-on (100M+ downloads)",
                    "Invested in scalp biotech",
                    "Expanded AI-driven formulation",
                    "Acquired Deciem (niche innovation lab)",
                ],
                "strengths": [
                    "Most innovative R&D in beauty (patent leader)",
                    "Luxury + mass dual-brand strategy",
                    "Direct-to-consumer digital leadership",
                    "Premium positioning command",
                ],
                "weaknesses": [
                    "Limited in mass-market detergents/laundry",
                    "Sustainability claims under scrutiny",
                    "Higher cost structure limits price competitiveness",
                ],
                "category_threat_level": {
                    "Hair: Color": "Very High",
                    "Hair: Care": "Very High",
                    "Hair: Styling": "High",
                    "LHC: FCN": "Low",
                },
            },
        },
        "market_dynamics": {
            "market_size_emea": {
                "Hair: Color": "€3.2B (2024 est.)",
                "Hair: Care": "€6.1B",
                "Hair: Styling": "€1.8B",
                "Hair: Body": "€2.4B",
                "LHC: FCN": "€4.8B",
                "LHC: FCA": "€3.2B",
            },
            "cagr_2020_2024": {
                "Hair: Color": "-0.5%",
                "Hair: Care": "+2.1%",
                "Hair: Styling": "+1.8%",
                "Hair: Body": "+3.5%",
                "LHC: FCN": "-1.2%",
                "LHC: FCA": "-0.8%",
            },
            "private_label_penetration": {
                "Hair: Color": "28%",
                "Hair: Care": "32%",
                "LHC: FCN": "42%",
                "LHC: FCA": "38%",
            },
            "e_commerce_penetration": {
                "Hair: Color": "18%",
                "Hair: Care": "22%",
                "LHC: FCN": "12%",
            },
            "key_trends": [
                "Premiumization accelerating in Color (+8% CAGR premium segment)",
                "Private label gaining share across all categories",
                "Waterless/concentrated formats growing (15% CAGR)",
                "DTC brands capturing niche segments",
                "Sustainability claims driving +5-10% price premium",
            ],
        },
        "category_competitive_intensity": {
            "Hair: Color": {
                "intensity": "Very High",
                "top_players": ["P&G (Pantene)", "L'Oréal (Paris)", "Henkel (Schwarzkopf)", "Unilever (Clairol)"],
                "margin_trend": "Declining (private label pressure)",
                "key_differentiators": ["Natural positioning", "Scalp health", "Personalization", "Professional partnerships"],
                "threat_level_to_henkel": "High",
            },
            "Hair: Care": {
                "intensity": "High",
                "top_players": ["P&G (Pantene, H&S)", "L'Oréal (Kérastase)", "Unilever (Dove)", "Henkel (Schwarzkopf)"],
                "margin_trend": "Stable (but shifting to premium)",
                "key_differentiators": ["Specialized functions", "Natural ingredients", "Multi-step routines"],
                "threat_level_to_henkel": "High",
            },
            "LHC: FCN": {
                "intensity": "Very High",
                "top_players": ["P&G (Tide)", "Unilever (Persil)", "Reckitt (Lysol)", "Henkel (Persil)", "Private label"],
                "margin_trend": "Declining sharply",
                "key_differentiators": ["Cold-water performance", "Sustainability", "Price-to-efficacy"],
                "threat_level_to_henkel": "Very High",
            },
        },
    }


def get_emerging_trends() -> list[dict]:
    """Return AI-curated emerging trends from simulated API sources.

    These are trends not yet in the main trend database but detected
    by scanning news, regulatory, patent, and academic sources.
    """
    return [
        {
            "id": "emerging_001",
            "name": "AI Hair Color Formulation via Generative Chemistry",
            "description": "Generative AI models are being used to design novel hair color molecules with reduced allergen profiles. L'Oréal and P&G have filed 12+ patents in Q1 2026.",
            "force": "Technology",
            "suggested_gp1_pct_affected": 0.15,
            "suggested_probability": 3,
            "direction": "Expansion",
            "relevance_score": 88,
            "category_mapping": {"Hair: Color": 5, "Hair: Care": 2},
            "sources": [
                {"name": "EPO Patent Filing", "api": "epo_patents", "url": "https://worldwide.espacenet.com"},
                {"name": "Nature Chemistry", "api": "semantic_scholar", "url": "https://www.nature.com/nchem/"},
            ],
            "ai_reasoning": "Direct threat to Henkel's Schwarzkopf color chemistry IP. P&G and L'Oréal are investing heavily in AI-driven formulation, potentially leapfrogging traditional R&D.",
            "detected_date": "2026-03-20",
            "confidence": "High",
        },
        {
            "id": "emerging_002",
            "name": "EU Microplastics Ban Phase 2 — Rinse-off Products by 2028",
            "description": "European Commission confirmed Phase 2 timeline for complete microplastics elimination in rinse-off cosmetics and detergents. Affects ~40% of current formulations.",
            "force": "Government",
            "suggested_gp1_pct_affected": 0.22,
            "suggested_probability": 4,
            "direction": "Contraction",
            "relevance_score": 95,
            "category_mapping": {"Hair: Care": 4, "Hair: Styling": 3, "LHC: FCN": 5, "LHC: FCA": 4},
            "sources": [
                {"name": "EUR-Lex Official Journal", "api": "eurlex", "url": "https://eur-lex.europa.eu"},
                {"name": "Chemical Watch", "api": "rss_feeds", "url": "https://chemicalwatch.com"},
            ],
            "ai_reasoning": "Major reformulation cost driver across Hair and LHC. Henkel's Persil and Schwarzkopf lines require significant reformulation. Early compliance could be a competitive advantage.",
            "detected_date": "2026-03-18",
            "confidence": "Very High",
        },
        {
            "id": "emerging_003",
            "name": "Refill Station Rollout Accelerating in DACH Retail",
            "description": "dm and Rossmann expanding in-store refill stations to 2,000+ locations by H2 2026. Covers laundry detergent, dish soap, and shampoo categories.",
            "force": "Customer",
            "suggested_gp1_pct_affected": 0.08,
            "suggested_probability": 4,
            "direction": "Expansion",
            "relevance_score": 82,
            "category_mapping": {"LHC: FCN": 4, "LHC: HDW": 3, "Hair: Care": 3},
            "sources": [
                {"name": "RetailDive Europe", "api": "rss_feeds", "url": "https://www.retaildive.com"},
                {"name": "dm Pressemitteilung", "api": "gnews", "url": "https://www.dm.de"},
            ],
            "ai_reasoning": "Creates new revenue opportunity for concentrated formulations. Henkel well-positioned with Persil and Pril concentrates. Risk: private label could capture refill share.",
            "detected_date": "2026-03-15",
            "confidence": "High",
        },
        {
            "id": "emerging_004",
            "name": "Scalp Microbiome Science Driving Premium Hair Care Segment",
            "description": "Clinical trials show scalp microbiome-targeted products deliver 3x better efficacy for dandruff and scalp health. Consumer search volume up 180% YoY.",
            "force": "Consumer",
            "suggested_gp1_pct_affected": 0.15,
            "suggested_probability": 3,
            "direction": "Expansion",
            "relevance_score": 79,
            "category_mapping": {"Hair: Care": 5, "Hair: Color": 2, "Hair: Body": 3},
            "sources": [
                {"name": "Google Trends", "api": "google_trends", "url": "https://trends.google.com"},
                {"name": "PubMed", "api": "semantic_scholar", "url": "https://pubmed.ncbi.nlm.nih.gov"},
            ],
            "ai_reasoning": "Premiumization opportunity for Schwarzkopf Professional line. L'Oréal already launched microbiome-targeted Kérastase sub-line. First-mover disadvantage if Henkel delays.",
            "detected_date": "2026-03-12",
            "confidence": "Medium",
        },
        {
            "id": "emerging_005",
            "name": "Water-Scarcity Laundry Innovation — Dry Wash Technologies",
            "description": "Water-free and ultra-low-water laundry technologies gaining traction in Southern Europe and Middle East. Unilever piloting dry-clean consumer products.",
            "force": "Environmental",
            "suggested_gp1_pct_affected": 0.08,
            "suggested_probability": 2,
            "direction": "Expansion",
            "relevance_score": 71,
            "category_mapping": {"LHC: FCN": 4, "LHC: FCA": 3, "LHC: FFI": 2},
            "sources": [
                {"name": "World Bank Water Data", "api": "world_bank", "url": "https://data.worldbank.org"},
                {"name": "Unilever Annual Report", "api": "sec_edgar", "url": "https://www.sec.gov/cgi-bin/browse-edgar"},
            ],
            "ai_reasoning": "Long-term structural shift in laundry formulation. Current probability low but impact could be transformational. Henkel should monitor and prepare concentrated formulation IP.",
            "detected_date": "2026-03-10",
            "confidence": "Medium",
        },
        {
            "id": "emerging_006",
            "name": "Amazon Private Label Hair Care Expansion in Europe",
            "description": "Amazon launching premium-positioned private label hair care under 'Belei' brand across DE, FR, UK. Leveraging consumer review data for product development.",
            "force": "Competitive",
            "suggested_gp1_pct_affected": 0.15,
            "suggested_probability": 3,
            "direction": "Contraction",
            "relevance_score": 85,
            "category_mapping": {"Hair: Care": 4, "Hair: Styling": 3, "Hair: Color": 2},
            "sources": [
                {"name": "GDELT News", "api": "gdelt", "url": "https://www.gdeltproject.org"},
                {"name": "Amazon.de", "api": "gnews", "url": "https://www.amazon.de"},
            ],
            "ai_reasoning": "Direct threat to Schwarzkopf's mass-market positioning. Amazon's data advantage enables precise product-market fit. Defend via professional/salon differentiation.",
            "detected_date": "2026-03-08",
            "confidence": "High",
        },
        {
            "id": "emerging_007",
            "name": "TikTok Shop Launch in DACH — Social Commerce for Beauty",
            "description": "TikTok Shop expanding to Germany and Austria in Q2 2026. Beauty and personal care expected to be #1 category based on UK/US launch data.",
            "force": "Customer",
            "suggested_gp1_pct_affected": 0.08,
            "suggested_probability": 4,
            "direction": "Expansion",
            "relevance_score": 76,
            "category_mapping": {"Hair: Color": 3, "Hair: Care": 4, "Hair: Styling": 4, "Hair: Body": 3},
            "sources": [
                {"name": "GNews", "api": "gnews", "url": "https://gnews.io"},
                {"name": "CurrentsAPI", "api": "currentsapi", "url": "https://currentsapi.services"},
            ],
            "ai_reasoning": "New channel opportunity for Hair brands. Schwarzkopf's mass positioning suits social commerce. Risk of channel conflict with traditional retail partners.",
            "detected_date": "2026-03-05",
            "confidence": "High",
        },
        {
            "id": "emerging_008",
            "name": "Bioethanol-Based Surfactants Reaching Price Parity",
            "description": "New bioethanol surfactant production at scale reaching cost parity with petrochemical alternatives. Could transform detergent and cleaning product formulation economics.",
            "force": "Technology",
            "suggested_gp1_pct_affected": 0.08,
            "suggested_probability": 2,
            "direction": "Expansion",
            "relevance_score": 68,
            "category_mapping": {"LHC: FCN": 4, "LHC: HDW": 3, "LHC: FCA": 3, "LHC: ADW": 2},
            "sources": [
                {"name": "Semantic Scholar", "api": "semantic_scholar", "url": "https://www.semanticscholar.org"},
                {"name": "FRED Commodity Data", "api": "fred", "url": "https://fred.stlouisfed.org"},
            ],
            "ai_reasoning": "Cost-neutral sustainability improvement. Henkel's Düsseldorf R&D center has active bio-surfactant program. Early adoption could drive margin + sustainability narrative.",
            "detected_date": "2026-03-01",
            "confidence": "Medium",
        },
    ]
