"""
seed_journey_exposure.py - Consumer-journey stage exposure per trend.

PROVENANCE: AI-suggested (2026-06-10), derived from the curated journey
tile map (data/consumerJourney.ts): for each trend x stage, exposure is
the max tile intensity citing that trend at that stage, mapped
{mild:2, moderate:3, strong:5} on the 0-5 exposure scale used by the
category/vc/regional exposure dimensions. Pending strategist review -
refine via the admin trend editor.

Stage keys are namespaced "<journey>:<stage_id>" with journey in
{lhc, hair} and stage ids matching data/consumerJourney.ts and
pulse/config.py JOURNEY_STAGES.
"""

JOURNEY_EXPOSURE = {
    "competitive_r01": {"lhc:washing_cycle": 3},
    "competitive_r02": {"hair:transform": 3},
    "competitive_r03": {"hair:transform": 3},
    "competitive_r04": {"hair:remedy": 3},
    "competitive_r05": {"hair:lock_finish": 5},
    "competitive_r06": {"hair:maintain_optimize": 3},
    "competitive_r07": {"hair:diagnose": 5},
    "competitive_r08": {"hair:remedy": 5},
    "competitive_r09": {"hair:prepare": 5},
    "competitive_r10": {"lhc:add_products": 5},
    "competitive_r11": {"hair:diagnose": 5},
    "competitive_r12": {"hair:inspire": 3},
    "competitive_r13": {"hair:transform": 5, "lhc:add_products": 5},
    "competitive_r14": {"hair:maintain_optimize": 3, "hair:prepare": 5},
    "consumer_r01": {"hair:transform": 5, "lhc:add_products": 5, "lhc:pre_treating": 5},
    "consumer_r02": {"hair:diagnose": 2},
    "consumer_r03": {"hair:diagnose": 3, "hair:inspire": 3, "hair:lock_finish": 5, "hair:maintain_optimize": 5, "hair:prepare": 3, "hair:refresh_between": 3, "hair:remedy": 5, "hair:transform": 5, "lhc:add_products": 3, "lhc:folding_storing": 3, "lhc:wearing": 3},
    "consumer_r04": {"hair:lock_finish": 2, "hair:prepare": 3, "lhc:add_products": 3, "lhc:between_washes": 2, "lhc:drying": 3, "lhc:folding_storing": 3, "lhc:ironing": 3, "lhc:pre_treating": 3, "lhc:taking_out": 3, "lhc:unloading": 3, "lhc:wearing": 3},
    "consumer_r05": {"hair:diagnose": 3, "hair:maintain_optimize": 3, "hair:remedy": 5, "hair:transform": 2, "lhc:ironing": 3, "lhc:sorting": 2},
    "consumer_r06": {"hair:maintain_optimize": 2, "hair:refresh_between": 3, "hair:transform": 5, "lhc:add_products": 5, "lhc:between_washes": 3, "lhc:ironing": 3, "lhc:taking_out": 3},
    "consumer_r07": {"hair:prepare": 3, "hair:refresh_between": 3, "hair:remedy": 5},
    "consumer_r08": {"hair:diagnose": 3, "hair:inspire": 3, "hair:refresh_between": 3},
    "consumer_r09": {"hair:lock_finish": 3, "hair:maintain_optimize": 2, "lhc:drying": 5},
    "consumer_r10": {"hair:diagnose": 5, "hair:maintain_optimize": 3, "hair:remedy": 5, "hair:transform": 3},
    "consumer_r11": {"hair:inspire": 3, "hair:transform": 3},
    "consumer_r13": {"lhc:pre_treating": 3},
    "consumer_r14": {"lhc:between_washes": 5},
    "consumer_r15": {"hair:refresh_between": 5},
    "consumer_r16": {"hair:inspire": 5},
    "consumer_r17": {"hair:prepare": 5},
    "consumer_r18": {"hair:remedy": 5, "lhc:add_products": 3},
    "consumer_r19": {"hair:inspire": 5},
    "consumer_r20": {"hair:transform": 3},
    "consumer_r21": {"hair:diagnose": 3, "hair:remedy": 3},
    "consumer_r22": {"lhc:add_products": 2},
    "consumer_r23": {"hair:remedy": 2},
    "consumer_r24": {"hair:lock_finish": 3, "hair:prepare": 3},
    "consumer_r25": {"lhc:add_products": 2},
    "consumer_r26": {"hair:inspire": 3},
    "consumer_r27": {"lhc:add_products": 3},
    "consumer_r28": {"lhc:add_products": 3},
    "consumer_r29": {"lhc:add_products": 3},
    "consumer_r30": {"lhc:between_washes": 3},
    "consumer_r31": {"lhc:pre_treating": 3},
    "consumer_r32": {"hair:diagnose": 3, "hair:remedy": 3},
    "consumer_r33": {"hair:lock_finish": 5},
    "customer_r01": {"lhc:add_products": 3},
    "customer_r02": {"hair:maintain_optimize": 3},
    "customer_r03": {"lhc:add_products": 5},
    "customer_r04": {"hair:inspire": 5, "hair:refresh_between": 3, "lhc:ironing": 3, "lhc:select_wash": 3, "lhc:sorting": 3, "lhc:taking_out": 2},
    "customer_r06": {"hair:maintain_optimize": 5, "lhc:add_products": 3, "lhc:pre_treating": 3, "lhc:washing_cycle": 3},
    "customer_r07": {"hair:lock_finish": 3, "hair:refresh_between": 3, "hair:transform": 5, "lhc:wearing": 3},
    "customer_r08": {"hair:inspire": 5, "lhc:add_products": 5},
    "customer_r09": {"lhc:add_products": 5},
    "customer_r10": {"hair:inspire": 3},
    "customer_r11": {"lhc:add_products": 3},
    "environmental_r01": {"lhc:add_products": 3},
    "environmental_r02": {"lhc:add_products": 5, "lhc:between_washes": 3, "lhc:drying": 5, "lhc:folding_storing": 2, "lhc:taking_out": 3, "lhc:unloading": 3, "lhc:washing_cycle": 3},
    "environmental_r03": {"lhc:add_products": 3},
    "environmental_r04": {"lhc:add_products": 3},
    "environmental_r05": {"hair:maintain_optimize": 2, "lhc:folding_storing": 3},
    "environmental_r06": {"lhc:add_products": 3},
    "environmental_r07": {"lhc:select_wash": 3, "lhc:washing_cycle": 3},
    "environmental_r08": {"lhc:drying": 3, "lhc:wearing": 2},
    "environmental_r09": {"lhc:add_products": 3},
    "environmental_r10": {"lhc:washing_cycle": 5},
    "environmental_r11": {"lhc:add_products": 3},
    "government_r01": {"lhc:add_products": 5, "lhc:folding_storing": 3, "lhc:pre_treating": 5, "lhc:wearing": 3},
    "government_r02": {"lhc:add_products": 5, "lhc:drying": 3, "lhc:loading": 5, "lhc:pre_treating": 5, "lhc:unloading": 3, "lhc:wearing": 3},
    "government_r03": {"hair:prepare": 3, "lhc:add_products": 3, "lhc:pre_treating": 5},
    "government_r04": {"hair:lock_finish": 2, "lhc:add_products": 5, "lhc:drying": 3, "lhc:wearing": 3},
    "government_r05": {"hair:lock_finish": 3, "lhc:add_products": 3, "lhc:between_washes": 2, "lhc:drying": 3, "lhc:pre_treating": 3, "lhc:unloading": 3, "lhc:wearing": 2},
    "government_r06": {"lhc:add_products": 3, "lhc:wearing": 3},
    "government_r07": {"lhc:sorting": 3},
    "government_r08": {"lhc:add_products": 3},
    "government_r09": {"lhc:add_products": 5},
    "government_r10": {"hair:diagnose": 3},
    "government_r11": {"lhc:add_products": 3},
    "government_r12": {"lhc:wearing": 2},
    "government_r13": {"hair:transform": 3},
    "government_r14": {"lhc:add_products": 5},
    "technology_r01": {"hair:diagnose": 5, "hair:inspire": 5, "hair:lock_finish": 5, "hair:maintain_optimize": 5, "hair:prepare": 5, "hair:refresh_between": 3, "hair:transform": 5, "lhc:add_products": 5, "lhc:between_washes": 3, "lhc:folding_storing": 3, "lhc:ironing": 3, "lhc:pre_treating": 5, "lhc:select_wash": 3, "lhc:sorting": 5, "lhc:washing_cycle": 5, "lhc:wearing": 5},
    "technology_r02": {"hair:lock_finish": 3, "hair:maintain_optimize": 5, "hair:prepare": 3, "hair:remedy": 2, "hair:transform": 3, "lhc:add_products": 5, "lhc:between_washes": 3, "lhc:folding_storing": 3, "lhc:pre_treating": 5, "lhc:taking_out": 3, "lhc:wearing": 5},
    "technology_r03": {"hair:refresh_between": 3, "lhc:add_products": 5, "lhc:between_washes": 3, "lhc:ironing": 3, "lhc:loading": 3, "lhc:pre_treating": 3, "lhc:taking_out": 3, "lhc:unloading": 5, "lhc:wearing": 2},
    "technology_r04": {"hair:diagnose": 5, "hair:maintain_optimize": 3, "hair:remedy": 3},
    "technology_r05": {"hair:lock_finish": 2, "hair:maintain_optimize": 3, "hair:prepare": 2, "hair:refresh_between": 2, "hair:remedy": 3, "hair:transform": 2, "lhc:between_washes": 3, "lhc:ironing": 3, "lhc:loading": 3, "lhc:pre_treating": 3, "lhc:select_wash": 5, "lhc:washing_cycle": 5},
    "technology_r06": {"hair:maintain_optimize": 3},
    "technology_r07": {"hair:diagnose": 5, "hair:inspire": 5, "hair:maintain_optimize": 2, "hair:prepare": 2, "hair:refresh_between": 3, "hair:remedy": 2, "hair:transform": 3, "lhc:add_products": 3, "lhc:between_washes": 2, "lhc:folding_storing": 3, "lhc:loading": 2, "lhc:select_wash": 3, "lhc:sorting": 5},
    "technology_r08": {"hair:maintain_optimize": 2, "hair:remedy": 2, "lhc:add_products": 5, "lhc:between_washes": 3, "lhc:drying": 3, "lhc:folding_storing": 3, "lhc:ironing": 5, "lhc:loading": 3, "lhc:select_wash": 5, "lhc:sorting": 5, "lhc:taking_out": 2, "lhc:unloading": 2, "lhc:washing_cycle": 5},
    "technology_r10": {"hair:inspire": 3},
    "technology_r11": {"lhc:add_products": 5},
    "technology_r12": {"lhc:add_products": 5},
    "technology_r13": {"hair:inspire": 5},
    "technology_r14": {"hair:remedy": 3},
    "technology_r15": {"lhc:add_products": 5},
    "technology_r16": {"lhc:add_products": 5},
    "technology_r17": {"hair:lock_finish": 3, "lhc:folding_storing": 3},
    "technology_r18": {"lhc:between_washes": 3},
    "technology_r19": {"lhc:unloading": 2},
}
